//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Vaksin_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warga
    {
        public string nik { get; set; }
        public string nama { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string alamat { get; set; }
        public string noHp { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
